server:
  port: 18089
spring:
  application:
    name: ribbon-order
  zipkin:
    base-url: http://192.168.211.132:9411
  sleuth:
    sampler:
      probability: 1 #采样率值介于0-1之间,1位全部采集
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000  #熔断器超时时间(毫秒)
#设置feign客户端超时时间(openfeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间,适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
logging:
  level:
    #feign日志以什么级别监控那个接口
    com.changgou.order.feign: debug
management:
  health:
    redis:
      enabled: false