server:
  port: 8401
spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.211.132:1111
    sentinel:
      transport:
        dashboard: 192.168.211.132:8081 #配置Sentinel dashboard地址
        port: 8719 #默认8719端口,假如占用会自动从8719开始一次+1扫描,直至找到未被占用的端口
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.211.132:1111
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'