server:
  port: 83
spring:
  application:
    name: nacos-consumer
  zipkin:
    base-url: http://192.168.211.132:9411
  sleuth:
    sampler:
      probability: 1 #采样率值介于0-1之间,1位全部采集
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.211.132:1111
        #server-addr: 192.168.211.132:8848
        #server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: 192.168.211.132:8081 #配置Sentinel dashboard地址
        port: 8719 #默认8719端口,假如占用会自动从8719开始一次+1扫描,直至找到未被占用的端口
#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
service-url:
  nacos-user-service: http://nacos-provider
management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true
