server:
  port: 9002
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.211.132:1111
        #server-addr: 192.168.211.132:8848
        #server-addr: localhost:8848
management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
